version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8001"
    volumes:
      - ./:/app
    ports:
      - "8001:8001"

  postgres:
    image: postgres:14
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: