# Generated by Django 4.0.5 on 2022-07-03 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lat", models.IntegerField()),
                ("lon", models.IntegerField()),
                ("destination", models.CharField(max_length=100)),
                ("alerts", models.JSONField()),
            ],
        ),
    ]
